### PR TITLE
Use latest versions in the test matrix

### PR DESCRIPTION
**Pull request by WouterJ**

### CODE REVIEW

**Comment by WouterJ** [comment]
@lsmith77 I wonder if we shouldn't merge this to 1.3-dev only?

**Comment by lsmith77** [comment]
ah .. we didn't branch of 1.2 yet?
I guess we should do that now .. so that master in all repos is the next major/minor release

**Comment by WouterJ** [comment]
@lsmith77 yeah, agreed. Will you take that job (some bundles already have it) or do you want me to help?

**Comment by lsmith77** [comment]
I will do it just now

**Comment by WouterJ** [comment]
:+1:

**Comment by lsmith77** [comment]
created 1.2 for this Bundle based on 1.2.2

**Pull request merged**
