### PR TITLE
Test lower boundary of version constraints

### PR DESCRIPTION
**Pull request by WouterJ**

### CODE REVIEW

**Comment by lsmith77** [comment]
also needs jackalope/jackalope 1.1.0+

**Comment by dbu** [comment]
should we restart? or up the limit for the testing component?

**Comment by lsmith77** [comment]
looks promising https://travis-ci.org/symfony-cmf/BlockBundle/jobs/64563958

**Comment by lsmith77** [comment]
then again .. why are the other builds failing with the ``--force`` issue again?

**Comment by WouterJ** [comment]
@lsmith77 other builds should use the dev-master of Testing instead of 1.2, however I've now set the version constraint to the lowest_versions branch, which is based on 1.2. When we release a new 1.2 (which I will do once I'm sure we don't need to change any more versions), all tests will pass again.

**Comment by lsmith77** [comment]
ah good :)

**Comment by lsmith77** [comment]
didn't we already fix that one?

```
..............................................PHP Fatal error:  Call to undefined method Doctrine\ODM\PHPCR\Translation\LocaleChooser\LocaleChooser::setFallbackLocales() in /home/travis/build/symfony-cmf/BlockBundle/vendor/doctrine/phpcr-bundle/Doctrine/Bundle/PHPCRBundle/EventListener/LocaleListener.php on line 120
```

**Comment by WouterJ** [comment]
@lsmith77 for some reason, the build installed `symfony-cmf/testing` and not 1.2.6 (I have no clue on why...). I've now merged 1.2 into master of Testing, so the issue should be fixed now

**Pull request merged**
